# Generated by Django 5.2.14 on 2026-05-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_department_created_at_department_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
