# Generated by Django 5.2.14 on 2026-05-08 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InwardDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('sender', models.CharField(blank=True, max_length=255)),
                ('received_date', models.DateField()),
                ('classification', models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Internal'), ('CONFIDENTIAL', 'Confidential'), ('SECRET', 'Secret')], default='INTERNAL', max_length=50)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('REGISTERED', 'Registered'), ('CHIEF_SECRETARY_REVIEW', 'Chief Secretary Review'), ('ASSIGNED_TO_HOD', 'Assigned to HOD'), ('OFFICER_ACTION', 'Officer Action'), ('HOD_REVIEW', 'HOD Review'), ('CHIEF_SECRETARY_FINAL_REVIEW', 'Chief Secretary Final Review'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='RECEIVED', max_length=50)),
                ('paperless_document_id', models.PositiveIntegerField(blank=True, null=True)),
                ('paperless_document_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_documents', to=settings.AUTH_USER_MODEL)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officer_documents', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inward_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_date', '-created_at'],
            },
        ),
    ]
