# Generated by Django 5.2.14 on 2026-05-08 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_assignments_received', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='documents.inwarddocument')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentWorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('RECEIVED', 'Received'), ('REGISTERED', 'Registered'), ('CHIEF_SECRETARY_REVIEW', 'Chief Secretary Review'), ('ASSIGNED_TO_HOD', 'Assigned to HOD'), ('OFFICER_ACTION', 'Officer Action'), ('HOD_REVIEW', 'HOD Review'), ('CHIEF_SECRETARY_FINAL_REVIEW', 'Chief Secretary Final Review'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], max_length=50)),
                ('to_status', models.CharField(choices=[('RECEIVED', 'Received'), ('REGISTERED', 'Registered'), ('CHIEF_SECRETARY_REVIEW', 'Chief Secretary Review'), ('ASSIGNED_TO_HOD', 'Assigned to HOD'), ('OFFICER_ACTION', 'Officer Action'), ('HOD_REVIEW', 'HOD Review'), ('CHIEF_SECRETARY_FINAL_REVIEW', 'Chief Secretary Final Review'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_workflow_actions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='documents.inwarddocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
